[package]
name = "raytox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
ply-rs = "*"
rayon = "*"
itertools = "*"
indicatif = "*"
rand = "*"
